---
title: "Melkaanvoer en zuivelproductie 2006-2020"
output: html_document
---

Alle gewichten zijn x1000 en zijn in KG

```{r, echo=FALSE, fig.height=12, fig.width=12}
# Load the required libraries
library(ggplot2)
library(tidyverse)

# Read the CSV file
data <- read.delim("Visserij_en_aquacultuur__hoeveelheid.csv", sep = ";")
header_text <- c("Vissoort","Perioden", "Hoeveelheid")
colnames(data) <- header_text

#Pivot the data from long to wide format
data_wide <- data %>%
  pivot_wider(names_from = Vissoort, values_from = Hoeveelheid)

#intialize point P
p<-ggplot(data,aes(Perioden, Hoeveelheid, col=Vissoort))

# Create graph plot
p+geom_point()+facet_wrap(.~Vissoort, scales = "free", ncol=2) + geom_smooth(method = 'loess', formula = 'y ~ x') + theme(legend.position = "none")

```
Voeg hier beschijving to over grafieken ^ 

```{r, echo=FALSE, fig.height=14, fig.width=12}
#create boxplot plot with jitter
p+geom_boxplot()+ geom_jitter()+facet_wrap(.~Vissoort, scales = "free", nrow= 3 ) + theme(legend.position = "none")

```
Voeg hier beschijving to over boxplotten ^ 
```{r, echo=FALSE, fig.height=8, fig.width=12}



```