---
title: "Melkaanvoer en zuivelproductie 2006-2020"
output: html_document
---

```{r, echo=FALSE, fig.height=8, fig.width=12}
# Load the required libraries
library(ggplot2)
library(reshape2)
library(dplyr)

# Read the dataset
data1 <- read.csv("Melkaanvoer_en_zuivelproductie2016-2020.csv", sep = ";", dec = ",")
data2 <- read.csv("Melkaanvoer_en_zuivelproductie2011-2015.csv", sep = ";", dec = ",")
data3 <- read.csv("Melkaanvoer_en_zuivelproductie2006-2010.csv", sep = ";", dec = ",")
header_text <- c("Perioden","Hoeveelheid \n(1000 kg)", "Vetgehalte (%)", "Eiwitgehalte (%)", "Melkpoeder totaal \n(1000 kg)", "Niet-mager \nmelkpoeder \n(1000 kg)", "Mager melkpoeder \n(1000 kg)", "Gecondenseerde \nmelk \n(1000 kg)")

# Merge datasets
data <- rbind(data3, data2, data1)
colnames(data) <- header_text
data_long<- melt(data, id.vars=c("Perioden"))

#intialize point P
p<-ggplot(data_long,aes(Perioden, value, col=variable))

# Create graph plot
p+geom_point()+facet_wrap(.~variable, scales = "free", ncol=2) + geom_smooth(method = 'loess', formula = 'y ~ x') + theme(legend.position = "none")

```
In de grafiek hierboven worden verschillende catogorien in ten opzichte van de tijd laten zien.
```{r, echo=FALSE, fig.height=8, fig.width=12}

#create boxplot plot with jitter
p+geom_boxplot()+ geom_jitter()+facet_wrap(.~variable, scales = "free", nrow= 1 ) + theme(legend.position = "none")

#create linegraph plot
p+geom_line()+facet_wrap(.~variable, scales = "free", ncol=2)+ theme(legend.position = "none")

# Filter the specific variables and years
data_filtered2006 <- data_long %>% filter(variable %in% c("Niet-mager \nmelkpoeder \n(1000 kg)", "Mager melkpoeder \n(1000 kg)", "Gecondenseerde \nmelk \n(1000 kg)"), Perioden %in% c("2006"))
data_filtered2020 <- data_long %>% filter(variable %in% c("Niet-mager \nmelkpoeder \n(1000 kg)", "Mager melkpoeder \n(1000 kg)", "Gecondenseerde \nmelk \n(1000 kg)"), Perioden %in% c("2020"))

# Calculate the percentage relative to each other
data_percentage2006 <- data_filtered2006 %>%
  group_by(Perioden) %>%
  mutate(Percentage = value / sum(value) * 100)

data_percentage2020 <- data_filtered2020 %>%
  group_by(Perioden) %>%
  mutate(Percentage = value / sum(value) * 100)

# Create barplot
p2020 <- ggplot(data_percentage2006, aes(x = Perioden, y = Percentage, fill = variable))
p2020 + geom_bar(stat = "identity", position = "dodge") + ggtitle("Productie van verschillende melkpoeders in 2006") + theme(legend.position = "top")

p2006 <- ggplot(data_percentage2020, aes(x = Perioden, y = Percentage, fill=variable))
p2006+geom_bar(stat = "identity", position = "dodge") + ggtitle("Productie van verschillende melkpoeders in 2020") + theme(legend.position = "none")
```